call vimtex#options#init()
call vimtex#delim#init_buffer()
call vimtex#matchparen#init_buffer()
call vimtex#text_obj#init_buffer()

"nmap <silent><buffer> ds$ <plug>(vimtex-env-delete-math)
"nmap <silent><buffer> cs$ <plug>(vimtex-env-change-math)
nmap <silent><buffer> dse <plug>(vimtex-env-delete)
nmap <silent><buffer> cse <plug>(vimtex-env-change)
"nmap <silent><buffer> tsf <plug>(vimtex-env-toggle) " don't understand how to
"use
nmap <silent><buffer> tss <plug>(vimtex-env-toggle-star)
"nmap <silent><buffer> ts$ <plug>(vimtex-env-toggle-math)
nmap <silent><buffer> <F6> <plug>(vimtex-env-surround-line)
xmap <silent><buffer> <F6> <plug>(vimtex-env-surround-visual)

"commands 
nmap <silent><buffer> dsc <plug>(vimtex-cmd-delete) 
nmap <silent><buffer> csc <plug>(vimtex-cmd-change)
nmap <silent><buffer> tsc <plug>(vimtex-cmd-toggle-star)
nmap <silent><buffer> tse <plug>(vimtex-cmd-toggle-frac)
xmap <silent><buffer> tse <plug>(vimtex-cmd-toggle-frac)
nmap <silent><buffer> tsb <plug>(vimtex-cmd-toggle-break)
"imap <silent><buffer> <F7> <plug>(vimtex-cmd-create)
nmap <silent><buffer> <F7> <plug>(vimtex-cmd-create)
xmap <silent><buffer> <F7> <plug>(vimtex-cmd-create)

nmap <silent><buffer> dsf <plug>(vimtex-delim-delete)
nmap <silent><buffer> csf <plug>(vimtex-delim-change-math)
nmap <silent><buffer> tsf <plug>(vimtex-delim-toggle-modifier)
xmap <silent><buffer> tsf <plug>(vimtex-delim-toggle-modifier)
"nmap <silent><buffer> tsD <plug>(vimtex-delim-toggle-modifier-reverse) "dont
"see why needed
"xmap <silent><buffer> tsD <plug>(vimtex-delim-toggle-modifier-reverse)
imap <silent><buffer> ]] <plug>(vimtex-delim-close)
"nmap <silent><buffer> <F8> <plug>(vimtex-delim-add-modifiers) "dont see why
"needed

nmap <silent><buffer> % <plug>(vimtex-%)
xmap <silent><buffer> % <plug>(vimtex-%)
omap <silent><buffer> % <plug>(vimtex-%)

" section boundaries
"nmap <silent><buffer> ]] <plug>(vimtex-]])
"nmap <silent><buffer> ][ <plug>(vimtex-][)
"nmap <silent><buffer> [] <plug>(vimtex-[])
"nmap <silent><buffer> [[ <plug>(vimtex-[[)
"xmap <silent><buffer> ]] <plug>(vimtex-]])
"xmap <silent><buffer> ][ <plug>(vimtex-][)
"xmap <silent><buffer> [] <plug>(vimtex-[])
"xmap <silent><buffer> [[ <plug>(vimtex-[[)
"omap <silent><buffer> ]] <plug>(vimtex-]])
"omap <silent><buffer> ][ <plug>(vimtex-][)
"omap <silent><buffer> [] <plug>(vimtex-[])
"omap <silent><buffer> [[ <plug>(vimtex-[[)

nmap <silent><buffer> ]] <plug>(vimtex-]M)
nmap <silent><buffer> ][ <plug>(vimtex-]m)
nmap <silent><buffer> [] <plug>(vimtex-[M)
nmap <silent><buffer> [[ <plug>(vimtex-[m)
xmap <silent><buffer> ]] <plug>(vimtex-]M)
xmap <silent><buffer> ][ <plug>(vimtex-]m)
xmap <silent><buffer> [] <plug>(vimtex-[M)
xmap <silent><buffer> [[ <plug>(vimtex-[m)
omap <silent><buffer> ]] <plug>(vimtex-]M)
omap <silent><buffer> ][ <plug>(vimtex-]m)
omap <silent><buffer> [] <plug>(vimtex-[M)
omap <silent><buffer> [[ <plug>(vimtex-[m)

" Math env detection weird
"nmap <silent><buffer> ]N <plug>(vimtex-]N)
"nmap <silent><buffer> ]n <plug>(vimtex-]n)
"nmap <silent><buffer> [N <plug>(vimtex-[N)
"nmap <silent><buffer> [n <plug>(vimtex-[n)
"xmap <silent><buffer> ]N <plug>(vimtex-]N)
"xmap <silent><buffer> ]n <plug>(vimtex-]n)
"xmap <silent><buffer> [N <plug>(vimtex-[N)
"xmap <silent><buffer> [n <plug>(vimtex-[n)
"omap <silent><buffer> ]N <plug>(vimtex-]N)
"omap <silent><buffer> ]n <plug>(vimtex-]n)
"omap <silent><buffer> [N <plug>(vimtex-[N)
"omap <silent><buffer> [n <plug>(vimtex-[n)

" No frame environment
"nmap <silent><buffer> ]R <plug>(vimtex-]R)
"nmap <silent><buffer> ]r <plug>(vimtex-]r)
"nmap <silent><buffer> [R <plug>(vimtex-[R)
"nmap <silent><buffer> [r <plug>(vimtex-[r)
"xmap <silent><buffer> ]R <plug>(vimtex-]R)
"xmap <silent><buffer> ]r <plug>(vimtex-]r)
"xmap <silent><buffer> [R <plug>(vimtex-[R)
"xmap <silent><buffer> [r <plug>(vimtex-[r)
"omap <silent><buffer> ]R <plug>(vimtex-]R)
"omap <silent><buffer> ]r <plug>(vimtex-]r)
"omap <silent><buffer> [R <plug>(vimtex-[R)
"omap <silent><buffer> [r <plug>(vimtex-[r)

" Comments weird 
"nmap <silent><buffer> ]/ <plug>(vimtex-]/)
"nmap <silent><buffer> ]* <plug>(vimtex-]*)
"nmap <silent><buffer> [/ <plug>(vimtex-[/)
"nmap <silent><buffer> [* <plug>(vimtex-[*)
"xmap <silent><buffer> ]/ <plug>(vimtex-]/)
"xmap <silent><buffer> ]* <plug>(vimtex-]*)
"xmap <silent><buffer> [/ <plug>(vimtex-[/)
"xmap <silent><buffer> [* <plug>(vimtex-[*)
"omap <silent><buffer> ]/ <plug>(vimtex-]/)
"omap <silent><buffer> ]* <plug>(vimtex-]*)
"omap <silent><buffer> [/ <plug>(vimtex-[/)
"omap <silent><buffer> [* <plug>(vimtex-[*)

omap <silent><buffer> ie <plug>(vimtex-ie)
omap <silent><buffer> ae <plug>(vimtex-ae)
xmap <silent><buffer> ie <plug>(vimtex-ie)
xmap <silent><buffer> ae <plug>(vimtex-ae)
xmap <silent><buffer> if <plug>(vimtex-id)
xmap <silent><buffer> af <plug>(vimtex-ad)
omap <silent><buffer> if <plug>(vimtex-id)
omap <silent><buffer> af <plug>(vimtex-ad)
"xmap <silent><buffer> i$ <plug>(vimtex-i$) "non functional 
"xmap <silent><buffer> a$ <plug>(vimtex-a$)
"omap <silent><buffer> i$ <plug>(vimtex-i$)
"omap <silent><buffer> a$ <plug>(vimtex-a$)
"xmap <silent><buffer> iP <plug>(vimtex-iP) "not needed
"xmap <silent><buffer> aP <plug>(vimtex-aP)
"omap <silent><buffer> iP <plug>(vimtex-iP)
"omap <silent><buffer> aP <plug>(vimtex-aP)
"xmap <silent><buffer> im <plug>(vimtex-im)
"xmap <silent><buffer> am <plug>(vimtex-am)
"omap <silent><buffer> im <plug>(vimtex-im)
"omap <silent><buffer> am <plug>(vimtex-am)
