local ls = require "luasnip"
local s = ls.snippet
local t = ls.text_node

return {}, {
  s({ trig = ";N", dscr = "\\nabla" }, { t "∇ " }),
  s({ trig = ";a", dscr = "\\alpha" }, { t "α" }),
  s({ trig = ";b", dscr = "\\beta" }, { t "β" }),
  s({ trig = ";g", dscr = "\\gamma" }, { t "γ" }),
  s({ trig = ";G", dscr = "\\Gamma" }, { t "Γ" }),
  s({ trig = ";d", dscr = "\\delta" }, { t "δ" }),
  s({ trig = ";D", dscr = "\\Delta" }, { t "Δ" }),
  s({ trig = ";e", dscr = "\\epsilon" }, { t "ϵ" }),
  s({ trig = ";ve", dscr = "\\varepsilon" }, { t "ε" }),
  s({ trig = ";z", dscr = "\\zeta" }, { t "ζ" }),
  s({ trig = ";h", dscr = "\\eta" }, { t "η" }),
  s({ trig = ";o", dscr = "\\theta" }, { t "θ" }),
  s({ trig = ";vo", dscr = "\\vartheta" }, { t "ϑ" }),
  s({ trig = ";O", dscr = "\\Theta" }, { t "Θ" }),
  s({ trig = ";k", dscr = "\\kappa" }, { t "κ" }),
  s({ trig = ";l", dscr = "\\lambda" }, { t "λ" }),
  s({ trig = ";L", dscr = "\\Lambda" }, { t "Λ" }),
  s({ trig = ";m", dscr = "\\mu" }, { t "μ" }),
  s({ trig = ";n", dscr = "\\nu" }, { t "ν" }),
  s({ trig = ";x", dscr = "\\xi" }, { t "ξ" }),
  s({ trig = ";X", dscr = "\\Xi" }, { t "Ξ" }),
  s({ trig = ";i", dscr = "\\pi" }, { t "π" }),
  s({ trig = ";I", dscr = "\\Pi" }, { t "Π" }),
  s({ trig = ";r", dscr = "\\rho" }, { t "ρ" }),
  s({ trig = ";s", dscr = "\\sigma" }, { t "σ" }),
  s({ trig = ";S", dscr = "\\Sigma" }, { t "Σ" }),
  s({ trig = ";t", dscr = "\\tau" }, { t "τ" }),
  s({ trig = ";f", dscr = "\\phi" }, { t "ϕ" }),
  s({ trig = ";vf", dscr = "\\varphi" }, { t "φ " }),
  s({ trig = ";F", dscr = "\\Phi" }, { t "Φ" }),
  s({ trig = ";c", dscr = "\\chi" }, { t "χ" }),
  s({ trig = ";p", dscr = "\\psi" }, { t "ψ" }),
  s({ trig = ";P", dscr = "\\Psi" }, { t "Ψ" }),
  s({ trig = ";w", dscr = "\\omega" }, { t "ω" }),
  s({ trig = ";W", dscr = "\\Omega" }, { t "Ω" }),
}
